### ISSUE TITLE
pundit-resources-1.1.1/lib/pundit/resource.rb:19: syntax error, unexpected '.' (SyntaxError)

### ISSUE THREAD

**Issue by rubyconvict** [togglepro/pundit-resources#25]
```
$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
```

```
Updating files in vendor/cache
  * pundit-resources-1.1.1.gem
Bundle complete! 85 Gemfile dependencies, 210 gems now installed.
Bundled gems are installed into ./vendor/bundle.

$ bundle exec rails s
/me/my_app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': /me/my_app/vendor/bundle/ruby/2.2.0/gems/pundit-resources-1.1.1/lib/pundit/resource.rb:19: syntax error, unexpected '.' (SyntaxError)
        context[:policy_used]&.call
                               ^
/me/my_app/vendor/bundle/ruby/2.2.0/gems/pundit-resources-1.1.1/lib/pundit/resource.rb:38: syntax error, unexpected '.'
        context[:policy_used]&.call
                               ^
/me/my_app/vendor/bundle/ruby/2.2.0/gems/pundit-resources-1.1.1/lib/pundit/resource.rb:44: syntax error, unexpected '.'
      context&.[](:current_user)
               ^
/me/my_app/vendor/bundle/ruby/2.2.0/gems/pundit-resources-1.1.1/lib/pundit/resource.rb:104: syntax error, unexpected end-of-input, expecting keyword_end
    from /me/my_app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
    from /me/my_app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /me/my_app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
    from /me/my_app/vendor/bundle/ruby/2.2.0/gems/pundit-resources-1.1.1/lib/pundit/resources.rb:2:in `<top (required)>'
    from /home/mkalita/.rvm/gems/ruby-2.2.4/gems/bundler-1.13.4/lib/bundler/runtime.rb:105:in `require'
    from /home/mkalita/.rvm/gems/ruby-2.2.4/gems/bundler-1.13.4/lib/bundler/runtime.rb:105:in `rescue in block in require'
    from /home/mkalita/.rvm/gems/ruby-2.2.4/gems/bundler-1.13.4/lib/bundler/runtime.rb:82:in `block in require'
    from /home/mkalita/.rvm/gems/ruby-2.2.4/gems/bundler-1.13.4/lib/bundler/runtime.rb:75:in `each'
    from /home/mkalita/.rvm/gems/ruby-2.2.4/gems/bundler-1.13.4/lib/bundler/runtime.rb:75:in `require'
    from /home/mkalita/.rvm/gems/ruby-2.2.4/gems/bundler-1.13.4/lib/bundler.rb:106:in `require'
    from /me/my_app/config/applicatio... 
(OMITTED)
```

**Comment by alyssais** [comment]
Yeah, that syntax requires Ruby 2.3+
